const appname = "eMart";
const appversion = "Version 1.0.0";
const credits = "@Harsh rathod";
const email = "Email";
const emailHint = "admin@admin.com";
const password = "Password";
const passwordHint = "*********";
const forgetPass = "Forget Password";
const retypePassword = "Retype Password";
const name = "Name";
const nameHint = "Harsh Rathod ";
const login = "Log in";
const signup = "Sign up";
const createNewAc = "Create a new account";
const loginWith = "Log in with";
const privacyPolicy = "Privacy Policy";
const termAndCond = "Terms and Conditions";
const alreadyHaveAccount = "Already have an account?";

const home = "Home",
    categories = "Categories",
    cart = "Cart",
    account = "Account";
